version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: erp-nginx
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - 8000:8088
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/